#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -ex

# these can't be in an venv because `opencv-python` does not work on Tegra
# ("Illegal Instruction" due to openblas, so we must use the system versions)
# this checks they're actually installed and importable
python3 -c "import cv2"
python3 -c "import numpy"

# clear any cached packages in our venv and install new ones
if ! [ -d "venv" ]; then
  pip3 install --upgrade virtualenv
  python3 -m virtualenv --system-site-packages -p python3 venv
	source venv/bin/activate
  # install requirements
  pip3 install -r requirements.txt
  pip3 install -r requirements.dev.txt
else
  source venv/bin/activate
fi

# run pytest
pytest -c setup.cfg

# commit coverage
git add cov.xml
